# Generated by Django 4.0 on 2022-01-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signed_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=250, unique=True)),
                ('u_email', models.EmailField(max_length=254)),
                ('u_pass', models.CharField(max_length=250)),
            ],
        ),
    ]
